In [1]:
import pandas as pd
import torch
import gymnasium as gym
from ars import run_ars
from aps import run_gaps
import matplotlib.pyplot as plt
from ars.ars_policy import ARSPolicy
from aps.gaps_policy import GAPSPolicy
from utils.normalizer import Normalizer
from utils.hyperparameters import ARSHyperparameters, GAPSHyperparameters

c:\Users\dscol\OneDrive\University of Chicago\Courses\CMSC 35401\APS\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


## HalfCheetah

In [2]:
torch.manual_seed(86)
env = gym.make("HalfCheetah-v4")
num_inputs = env.observation_space.shape[0]
num_outputs = env.action_space.shape[0]
gaps_policy = GAPSPolicy(num_inputs, num_outputs)
normalizer = Normalizer(num_inputs)
gaps_hp = GAPSHyperparameters(horizon=100)
best_theta, value = run_gaps.train(env, gaps_policy, normalizer, gaps_hp, 86)
trained_gaps_policy = GAPSPolicy(num_inputs, num_outputs)
trained_gaps_policy.theta = best_theta
gaps_hp.horizon = 1000
gaps_rewards = run_gaps.explore(env, gaps_hp, normalizer, trained_gaps_policy)

Experiment: 1
Experiment: 2
Experiment: 3
Experiment: 4
Experiment: 5
Experiment: 6
Experiment: 7
Experiment: 8
Experiment: 9
Experiment: 10
Experiment: 11
Experiment: 12
Experiment: 13
Experiment: 14
Experiment: 15
Experiment: 16
Experiment: 17
Experiment: 18
Experiment: 19
Experiment: 20
Experiment: 21
Experiment: 22
Experiment: 23
Experiment: 24
Experiment: 25
Experiment: 26
Experiment: 27
Experiment: 28
Experiment: 29
Experiment: 30
Experiment: 31
Experiment: 32
Experiment: 33
Experiment: 34
Experiment: 35
Experiment: 36
Experiment: 37
Experiment: 38
Experiment: 39
Experiment: 40
Experiment: 41
Experiment: 42
Experiment: 43
Experiment: 44
Experiment: 45
Experiment: 46
Experiment: 47
Experiment: 48
Experiment: 49
Experiment: 50
Experiment: 51
Experiment: 52
Experiment: 53
Experiment: 54
Experiment: 55
Experiment: 56
Experiment: 57
Experiment: 58
Experiment: 59
Experiment: 60
Experiment: 61
Experiment: 62
Experiment: 63
Experiment: 64
Experiment: 65
Experiment: 66
Experiment: 67
Expe

In [3]:
value

tensor(252.7307, dtype=torch.float64)

In [4]:
gaps_rewards

0.521725467793333

In [5]:
gaps_policy.theta

tensor([[ 0.0733,  0.2443,  0.1391, -0.3569, -0.0790, -0.1072,  0.2012,  0.1674,
          0.4440,  0.4809, -0.4023,  0.3393,  0.1514, -0.1992,  0.4845,  0.3389,
         -0.6538],
        [-0.2314, -0.6901, -0.1915, -0.2033, -0.5623,  0.4544,  0.3754,  0.5267,
          0.0014,  0.3156, -0.5000,  0.4193,  0.0299,  0.1043, -0.1974,  0.2040,
         -0.0199],
        [-0.1645,  0.3265,  0.1877, -0.3127,  0.1277, -0.4476, -0.4017, -0.1542,
         -0.1563, -0.7305,  0.2373,  0.4193,  0.6381, -0.5194, -0.2807, -0.4424,
          0.7059],
        [ 0.4331, -0.2006, -0.1085,  0.6452, -0.3054, -0.6418, -0.5409, -0.1829,
         -0.1726,  0.3741,  0.1381,  0.6336, -0.6157, -0.3658, -0.6940, -0.5740,
         -0.6339],
        [ 0.0376,  0.3130, -0.5793, -0.7275, -0.3568, -0.4957,  0.3524,  0.4955,
          0.1699,  0.4040,  0.2424, -0.1380, -0.3075,  0.2326,  0.7303, -0.0900,
         -0.5857],
        [-0.4604, -0.1551, -0.6061,  0.4234,  0.4713, -0.4858,  0.6875, -0.2119,
          0.74

In [13]:
env = gym.make("HalfCheetah-v4")
ars_hp = ARSHyperparameters(num_experiments=100, horizon=1000)
num_inputs = env.observation_space.shape[0]
num_outputs = env.action_space.shape[0]
ars_policy = ARSPolicy(ars_hp, num_inputs, num_outputs)
normalizer = Normalizer(num_inputs)
trained_ars_policy = run_ars.train(env, ars_policy, normalizer, ars_hp)
ars_hp.horizon = 1000
ars_rewards = run_ars.explore(env, ars_hp, normalizer, trained_ars_policy)

Experiment: 1
Experiment: 2
Experiment: 3
Experiment: 4
Experiment: 5
Experiment: 6
Experiment: 7
Experiment: 8
Experiment: 9
Experiment: 10
Experiment: 11
Experiment: 12
Experiment: 13
Experiment: 14
Experiment: 15
Experiment: 16
Experiment: 17
Experiment: 18
Experiment: 19
Experiment: 20
Experiment: 21
Experiment: 22
Experiment: 23
Experiment: 24
Experiment: 25
Experiment: 26
Experiment: 27
Experiment: 28
Experiment: 29
Experiment: 30
Experiment: 31
Experiment: 32
Experiment: 33
Experiment: 34
Experiment: 35
Experiment: 36
Experiment: 37
Experiment: 38
Experiment: 39
Experiment: 40
Experiment: 41
Experiment: 42
Experiment: 43
Experiment: 44
Experiment: 45
Experiment: 46
Experiment: 47
Experiment: 48
Experiment: 49
Experiment: 50
Experiment: 51
Experiment: 52
Experiment: 53
Experiment: 54
Experiment: 55
Experiment: 56
Experiment: 57
Experiment: 58
Experiment: 59
Experiment: 60
Experiment: 61
Experiment: 62
Experiment: 63
Experiment: 64
Experiment: 65
Experiment: 66
Experiment: 67
Expe

In [14]:
ars_rewards

-0.9787638137782251

In [8]:
trained_ars_policy.theta

tensor([[-3.4017e-02,  1.5866e-03,  1.5272e-01,  8.5299e-03,  2.8107e-02,
         -1.3827e-02, -1.8734e-02, -2.7089e-02, -6.8276e-03, -6.4990e-03,
          3.1175e-02, -1.2990e-01, -3.4468e-02,  1.3881e-03,  2.7970e-04,
          2.4618e-02, -1.6493e-02],
        [-5.9352e-02,  1.6167e-02,  2.8351e-02,  1.2652e-01,  3.2480e-02,
          6.3388e-03, -4.4591e-02, -9.6470e-03,  1.4744e-02,  2.4728e-02,
          7.8527e-02, -1.0129e-01, -9.3935e-02, -1.5999e-02, -1.6527e-02,
         -9.8344e-03, -4.9158e-03],
        [-1.4011e-02,  2.8505e-02,  3.3690e-02,  2.1881e-02,  6.3391e-02,
         -1.1072e-02,  6.2105e-03, -1.2291e-02,  1.5200e-04,  8.9602e-03,
          1.6630e-02, -2.7426e-02, -2.5151e-03, -9.8881e-02, -8.4345e-03,
         -1.3083e-03, -2.0212e-02],
        [ 3.2953e-02, -4.5897e-02,  4.1744e-02, -3.9376e-03, -4.4351e-03,
          2.4722e-01,  8.3002e-02,  6.3867e-02,  6.9407e-02,  2.8935e-02,
          8.1658e-02,  4.4613e-03, -1.6986e-02, -1.5233e-02, -1.5371e-01,
    

In [ ]:
trained_gaps_policy.theta

## Swimmer

In [9]:
torch.manual_seed(901)
env = gym.make("Swimmer-v4")
num_inputs = env.observation_space.shape[0]
num_outputs = env.action_space.shape[0]
gaps_policy = GAPSPolicy(num_inputs, num_outputs)
normalizer = Normalizer(num_inputs)
gaps_hp = GAPSHyperparameters(horizon=100)
best_theta, value = run_gaps.train(env, gaps_policy, normalizer, gaps_hp, 901)
trained_gaps_policy = GAPSPolicy(num_inputs, num_outputs)
trained_gaps_policy.theta = best_theta
gaps_hp.horizon = 1000
gaps_rewards = run_gaps.explore(env, gaps_hp, normalizer, trained_gaps_policy)

Experiment: 1
Experiment: 2
Experiment: 3
Experiment: 4
Experiment: 5
Experiment: 6
Experiment: 7
Experiment: 8
Experiment: 9
Experiment: 10
Experiment: 11
Experiment: 12
Experiment: 13
Experiment: 14
Experiment: 15
Experiment: 16
Experiment: 17
Experiment: 18
Experiment: 19
Experiment: 20
Experiment: 21
Experiment: 22
Experiment: 23
Experiment: 24
Experiment: 25
Experiment: 26
Experiment: 27
Experiment: 28
Experiment: 29
Experiment: 30
Experiment: 31
Experiment: 32
Experiment: 33
Experiment: 34
Experiment: 35
Experiment: 36
Experiment: 37
Experiment: 38
Experiment: 39
Experiment: 40
Experiment: 41
Experiment: 42
Experiment: 43
Experiment: 44
Experiment: 45
Experiment: 46
Experiment: 47
Experiment: 48
Experiment: 49
Experiment: 50
Experiment: 51
Experiment: 52
Experiment: 53
Experiment: 54
Experiment: 55
Experiment: 56
Experiment: 57
Experiment: 58
Experiment: 59
Experiment: 60
Experiment: 61
Experiment: 62
Experiment: 63
Experiment: 64
Experiment: 65
Experiment: 66
Experiment: 67
Expe

In [10]:
value

tensor(21.6888, dtype=torch.float64)

In [11]:
gaps_rewards

23.799727082779267

In [12]:
gaps_policy.theta

tensor([[ 7.4899e-01,  5.4792e-01,  7.3388e-01, -6.0059e-01,  7.1527e-01,
          4.0162e-01,  2.0171e-01,  1.8961e-01],
        [-1.6403e-01, -6.3306e-04,  3.2891e-01, -7.3769e-01, -2.2104e-01,
         -5.7414e-01,  2.3472e-01, -3.5053e-01]], dtype=torch.float64)

In [15]:
env = gym.make("Swimmer-v4")
ars_hp = ARSHyperparameters(num_experiments=100, horizon=1000)
num_inputs = env.observation_space.shape[0]
num_outputs = env.action_space.shape[0]
ars_policy = ARSPolicy(ars_hp, num_inputs, num_outputs)
normalizer = Normalizer(num_inputs)
trained_ars_policy = run_ars.train(env, ars_policy, normalizer, ars_hp)
ars_hp.horizon = 1000
ars_rewards = run_ars.explore(env, ars_hp, normalizer, trained_ars_policy)

Experiment: 1
Experiment: 2
Experiment: 3
Experiment: 4
Experiment: 5
Experiment: 6
Experiment: 7
Experiment: 8
Experiment: 9
Experiment: 10
Experiment: 11
Experiment: 12
Experiment: 13
Experiment: 14
Experiment: 15
Experiment: 16
Experiment: 17
Experiment: 18
Experiment: 19
Experiment: 20
Experiment: 21
Experiment: 22
Experiment: 23
Experiment: 24
Experiment: 25
Experiment: 26
Experiment: 27
Experiment: 28
Experiment: 29
Experiment: 30
Experiment: 31
Experiment: 32
Experiment: 33
Experiment: 34
Experiment: 35
Experiment: 36
Experiment: 37
Experiment: 38
Experiment: 39
Experiment: 40
Experiment: 41
Experiment: 42
Experiment: 43
Experiment: 44
Experiment: 45
Experiment: 46
Experiment: 47
Experiment: 48
Experiment: 49
Experiment: 50
Experiment: 51
Experiment: 52
Experiment: 53
Experiment: 54
Experiment: 55
Experiment: 56
Experiment: 57
Experiment: 58
Experiment: 59
Experiment: 60
Experiment: 61
Experiment: 62
Experiment: 63
Experiment: 64
Experiment: 65
Experiment: 66
Experiment: 67
Expe

In [16]:
ars_rewards

289.1240807944222

In [17]:
trained_ars_policy.theta

tensor([[ 0.5314, -0.1543, -0.7112, -0.0268,  0.6317, -0.1740,  0.2212,  0.0774],
        [-0.2993,  0.6722, -0.3582, -0.0017,  0.4822, -0.4887,  0.2931,  0.1983]])

## Walker

In [19]:
env = gym.make("Walker2d-v4")
num_inputs = env.observation_space.shape[0]
num_outputs = env.action_space.shape[0]
gaps_policy = GAPSPolicy(num_inputs, num_outputs)
normalizer = Normalizer(num_inputs)
gaps_hp = GAPSHyperparameters(horizon=1000)
best_theta, value = run_gaps.train(env, gaps_policy, normalizer, gaps_hp, 814)
trained_gaps_policy = GAPSPolicy(num_inputs, num_outputs)
trained_gaps_policy.theta = best_theta
gaps_hp.horizon = 1000
gaps_rewards = run_gaps.explore(env, gaps_hp, normalizer, trained_gaps_policy)

Experiment: 1
Experiment: 2
Experiment: 3
Experiment: 4
Experiment: 5
Experiment: 6
Experiment: 7
Experiment: 8
Experiment: 9
Experiment: 10
Experiment: 11
Experiment: 12
Experiment: 13
Experiment: 14
Experiment: 15
Experiment: 16
Experiment: 17
Experiment: 18
Experiment: 19
Experiment: 20
Experiment: 21
Experiment: 22
Experiment: 23
Experiment: 24
Experiment: 25
Experiment: 26
Experiment: 27
Experiment: 28
Experiment: 29
Experiment: 30
Experiment: 31
Experiment: 32
Experiment: 33
Experiment: 34
Experiment: 35
Experiment: 36
Experiment: 37
Experiment: 38
Experiment: 39
Experiment: 40
Experiment: 41
Experiment: 42
Experiment: 43
Experiment: 44
Experiment: 45
Experiment: 46
Experiment: 47
Experiment: 48
Experiment: 49
Experiment: 50
Experiment: 51
Experiment: 52
Experiment: 53
Experiment: 54
Experiment: 55
Experiment: 56
Experiment: 57
Experiment: 58
Experiment: 59
Experiment: 60
Experiment: 61
Experiment: 62
Experiment: 63
Experiment: 64
Experiment: 65
Experiment: 66
Experiment: 67
Expe

In [20]:
value

tensor(-1.2372, dtype=torch.float64)

In [21]:
gaps_rewards

-6.544518055249603

In [22]:
gaps_policy.theta

tensor([[-0.3195, -0.3125,  0.6673,  0.2735, -0.5980, -0.5722, -0.3178,  0.5003,
          0.0084,  0.3402, -0.7244,  0.6966,  0.3774, -0.3684,  0.4272,  0.4656,
          0.5978],
        [ 0.6354,  0.2447, -0.1581,  0.0013, -0.5187,  0.7107, -0.6499,  0.6267,
          0.6302, -0.1977, -0.7285,  0.5571,  0.0641,  0.3190,  0.7077,  0.3470,
          0.6077],
        [ 0.7326, -0.2104,  0.1909, -0.6148,  0.3515, -0.6083,  0.5401,  0.1866,
         -0.4982, -0.2473, -0.4651, -0.2176,  0.1168,  0.2751,  0.1347, -0.1358,
          0.2037],
        [-0.3896, -0.5878,  0.3757, -0.4448, -0.2396, -0.5164,  0.2574, -0.6995,
          0.5102,  0.3690,  0.4438, -0.7397,  0.5719,  0.2025,  0.1315, -0.4996,
          0.1246],
        [-0.1221, -0.6521,  0.1466, -0.5848, -0.6823,  0.2802, -0.1751,  0.6364,
         -0.2164, -0.3381, -0.5126, -0.0839,  0.2769, -0.2581,  0.5296, -0.3387,
         -0.1074],
        [-0.2879, -0.4185,  0.6367,  0.6208,  0.5411,  0.5678,  0.0363, -0.1299,
          0.12

In [23]:
env = gym.make("Walker2d-v4")
ars_hp = ARSHyperparameters(num_experiments=100, horizon=1000)
num_inputs = env.observation_space.shape[0]
num_outputs = env.action_space.shape[0]
ars_policy = ARSPolicy(ars_hp, num_inputs, num_outputs)
normalizer = Normalizer(num_inputs)
trained_ars_policy = run_ars.train(env, ars_policy, normalizer, ars_hp)
ars_hp.horizon = 1000
ars_rewards = run_ars.explore(env, ars_hp, normalizer, trained_ars_policy)

Experiment: 1
Experiment: 2
Experiment: 3
Experiment: 4
Experiment: 5
Experiment: 6
Experiment: 7
Experiment: 8
Experiment: 9
Experiment: 10
Experiment: 11
Experiment: 12
Experiment: 13
Experiment: 14
Experiment: 15
Experiment: 16
Experiment: 17
Experiment: 18
Experiment: 19
Experiment: 20
Experiment: 21
Experiment: 22
Experiment: 23
Experiment: 24
Experiment: 25
Experiment: 26
Experiment: 27
Experiment: 28
Experiment: 29
Experiment: 30
Experiment: 31
Experiment: 32
Experiment: 33
Experiment: 34
Experiment: 35
Experiment: 36
Experiment: 37
Experiment: 38
Experiment: 39
Experiment: 40
Experiment: 41
Experiment: 42
Experiment: 43
Experiment: 44
Experiment: 45
Experiment: 46
Experiment: 47
Experiment: 48
Experiment: 49
Experiment: 50
Experiment: 51
Experiment: 52
Experiment: 53
Experiment: 54
Experiment: 55
Experiment: 56
Experiment: 57
Experiment: 58
Experiment: 59
Experiment: 60
Experiment: 61
Experiment: 62
Experiment: 63
Experiment: 64
Experiment: 65
Experiment: 66
Experiment: 67
Expe

In [24]:
ars_rewards

327.0631509830997

In [25]:
trained_ars_policy.theta

tensor([[ 0.0195,  0.0618, -0.0609,  0.0003,  0.1283,  0.0157,  0.0088,  0.0771,
          0.1013,  0.0785,  0.0005, -0.0463,  0.0959, -0.0404, -0.0171, -0.0220,
          0.0972],
        [-0.0851,  0.0663,  0.0339,  0.0389,  0.0048,  0.0971,  0.0293,  0.2055,
          0.0451,  0.0116,  0.0267,  0.0651, -0.1550,  0.0081,  0.0470,  0.0315,
          0.1080],
        [ 0.0659,  0.2574,  0.0724,  0.1414, -0.0158,  0.0595,  0.1999,  0.1365,
          0.1626,  0.1237,  0.1126,  0.0839,  0.0379, -0.1628,  0.0279,  0.0419,
         -0.0053],
        [-0.0032,  0.0764,  0.0623,  0.0398,  0.0482,  0.0116,  0.0726,  0.0753,
          0.1457,  0.0301,  0.0068,  0.0527,  0.0019,  0.0696, -0.0023,  0.1535,
          0.0305],
        [ 0.0039,  0.1329,  0.0394,  0.0452,  0.1301,  0.1362, -0.0312,  0.0930,
          0.0575,  0.0620,  0.0808, -0.0017, -0.0004,  0.0246,  0.0708, -0.1561,
          0.0863],
        [-0.0342,  0.1269,  0.1853,  0.0833,  0.0694,  0.0813,  0.1003, -0.0171,
          0.12

## Hopper

In [26]:
env = gym.make("Hopper-v4")
num_inputs = env.observation_space.shape[0]
num_outputs = env.action_space.shape[0]
gaps_policy = GAPSPolicy(num_inputs, num_outputs)
normalizer = Normalizer(num_inputs)
gaps_hp = GAPSHyperparameters(horizon=1000)
best_theta, value = run_gaps.train(env, gaps_policy, normalizer, gaps_hp, 814)
trained_gaps_policy = GAPSPolicy(num_inputs, num_outputs)
trained_gaps_policy.theta = best_theta
gaps_hp.horizon = 1000
gaps_rewards = run_gaps.explore(env, gaps_hp, normalizer, trained_gaps_policy)

Experiment: 1
Experiment: 2
Experiment: 3
Experiment: 4
Experiment: 5
Experiment: 6
Experiment: 7
Experiment: 8
Experiment: 9
Experiment: 10
Experiment: 11
Experiment: 12
Experiment: 13
Experiment: 14
Experiment: 15
Experiment: 16
Experiment: 17
Experiment: 18
Experiment: 19
Experiment: 20
Experiment: 21
Experiment: 22
Experiment: 23
Experiment: 24
Experiment: 25
Experiment: 26
Experiment: 27
Experiment: 28
Experiment: 29
Experiment: 30
Experiment: 31
Experiment: 32
Experiment: 33
Experiment: 34
Experiment: 35
Experiment: 36
Experiment: 37
Experiment: 38
Experiment: 39
Experiment: 40
Experiment: 41
Experiment: 42
Experiment: 43
Experiment: 44
Experiment: 45
Experiment: 46
Experiment: 47
Experiment: 48
Experiment: 49
Experiment: 50
Experiment: 51
Experiment: 52
Experiment: 53
Experiment: 54
Experiment: 55
Experiment: 56
Experiment: 57
Experiment: 58
Experiment: 59
Experiment: 60
Experiment: 61
Experiment: 62
Experiment: 63
Experiment: 64
Experiment: 65
Experiment: 66
Experiment: 67
Expe